### ISSUE TITLE
Request for the preprocessed datasets

### ISSUE THREAD

**Issue by meaningful96** [canghongjian/beam_retriever#11]
Hi, thank you for sharing your great work!

Unfortunately, I'm facing an issue with preprocessing the data and training the model. Could you provide the preprocessed data(like google drive) and explain the training process in detail?

**Comment by canghongjian** [comment]
Hi, thanks for your interests! Just take HotpotQA as an example, you need to download the original data from the official website [train_file](http://curtis.ml.cmu.edu/datasets/hotpot/hotpot_train_v1.1.json) and [predict_file](http://curtis.ml.cmu.edu/datasets/hotpot/hotpot_dev_distractor_v1.json.). Then you can modify the startup bash file `run_train_beam_retr.sh` by passing the actual path of `train_file` and `predict_file`. After that, you can start training by running the command `sh run_train_beam_retr.sh`.

**Comment by meaningful96** [comment]
Thank you for your response. I was initially confused that i needed all the preprocessed datasets sampled by [IRCoT](https://github.com/StonyBrookNLP/ircot), but now I understand and believe I can handle it on my own. I sincerely appreciate your help once again.

**Comment by canghongjian** [comment]
Feel free to contact me if you have any other questions!
