### ISSUE TITLE
Query for training speed

### ISSUE THREAD

**Issue by CrazyShipOne** [canghongjian/beam_retriever#2]
Hi @canghongjian,

Thanks for your work in advance!

I'm trying to run `run_train_beam_retr.sh` with HotpotQA on a 32GB Tesla V100, but it took 24 hours to finish 1 epoch. Just wondering if am I doing something wrong here? Or there are ways to speed up training process?

Thanks!

**Comment by canghongjian** [comment]
> Hi @canghongjian,
> 
> Thanks for your work in advance!
> 
> I'm trying to run `run_train_beam_retr.sh` with HotpotQA on a 32GB Tesla V100, but it took 24 hours to finish 1 epoch. Just wondering if am I doing something wrong here? Or there are ways to speed up training process?
> 
> Thanks!

Thanks for your interest in our work!  Your results seem fine. There are several reasons for the slow training speed:
1. Training on HotpotQA does take time, as there are 90k training samples and 3 evaluation on 1 epoch. 
2. DP or DDP training is not supported now.
3. DeBERTa is incompatible with advanced attention method such as FlashAttention.
4. V100 is a bit slow.
5. The`gradient_checkpointing` is on.

Here are some solutions for those:
1. Increase the hyper-parameter `eval_period_ratio = 1` in the bash file.
2. Make the training code support DP or DDP (I will work on it in my free time).
3. Use models like RoBERTa which can utilize FlashAttention.
4. Use more faster GPUs such as 4090 (recommended) or A100.
5. Turn off the `gradient_checkpointing`, which will cost more memory (In my experience, V100 should be able to support the training of base version DeBERTa and a beam size of 1 without  gradient_checkpointing).

**Comment by CrazyShipOne** [comment]
Thanks for your advices! Let me try it and get back here if succeed.

**Comment by CrazyShipOne** [comment]
Hi @canghongjian,

Seems a lot of work should be done for DDP, even DeBERTa initialize all layers with 'None' pass to device, which cause device to be 'cpu' later...

Is that possible uploading a trained model if capable? It could save me two weeks to train it on my poor infrastructure...

Thanks a lot!

**Comment by canghongjian** [comment]
> Hi @canghongjian,
> 
> Seems a lot of work should be done for DDP, even DeBERTa initialize all layers with 'None' pass to device, which cause device to be 'cpu' later...
> 
> Is that possible uploading a trained model if capable? It could save me two weeks to train it on my poor infrastructure...
> 
> Thanks a lot!

Hey @CrazyShipOne . I have uploaded the large version of Beam Retrieval on HotpotQA:
[hotpot_beam1_retr.pt](https://drive.google.com/file/d/1-VAu64S11SxSHGxqVyOcALg_R8qdzHiP/view?pli=1)
[hotpot_beam2_retr.pt](https://drive.google.com/file/d/1LkPpjGUJkTwotGL0Luomy9IfU_S63UJ8/view?usp=sharing)
Hopefully they can help you with your issues, and looking forward to your feedback.

**Comment by CrazyShipOne** [comment]
@canghongjian It does help me a lot. Thanks!!!

**Comment by CrazyShipOne** [comment]
Hi @canghongjian,

I managed to train retriever and reader model in large batch size and plan to compare them with uploaded checkpoints.

But sorry for my poor experience on pyTorch, when trying to run 'test_model_tmp.py', I faced to the error:
```
Error(s) in loading state_dict for Reader:
	size mismatch for encoder.embeddings.word_embeddings.weight: copying a param with shape torch.Size([128003, 1024]) from checkpoint, the shape in current model is torch.Size([128100, 1024]).
File "conda/envs/st_training/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
  File "beam_retriever/test_model_tmp.py", line 32, in load_saved
    model.load_state_dict(state_dict)
  File "beam_retriever/test_model_tmp.py", line 272, in get_reader_qa_output
    qa_model = load_saved(qa_model, qa_checkpoint)
  File "beam_retriever/test_model_tmp.py", line 439, in <module>
    get_reader_qa_output(retr_json, test_raw_data, is_dev=is_dev, type=type, answer_merge=True, topk=10)
```
The reader model is trained with 'deepset/deberta-v3-large-squad2' and the same model path is set when calling 'load_saved'. I have no idea why it happened since they are exact the same model...

Thanks!

**Comment by canghongjian** [comment]
@CrazyShipOne The error might come from the mismatch between the init model and the loading checkpoint. Reader for HotpotQA and 2WikiMultihopQA requires two special tokens SEP and DOC. And the vocab size of model should be consistent with that of tokenizer, which is implemented in line 21 in `qa/reader_model.py`. Try to edit the 271 line in `test_model_tmp.py`:
```
qa_model = Reader(config, qa_model_path, len(tokenizer))
```

**Comment by CrazyShipOne** [comment]
It works like a charm!

Really appreciate your help!
