### ISSUE TITLE
关于检索内容的问题

### ISSUE THREAD

**Issue by fmm170** [canghongjian/beam_retriever#6]
您好！最近拜读了您的文章，又配合阅读了代码。想问一下根据query检索用来回答问题的相关文档，您是从哪里检索的呢？方便提供一下数据吗？谢谢啦～

**Comment by canghongjian** [comment]
你好，感谢关注！本项目目前主要针对阅读理解环境，即目标数据集都会对每个query给定包含10或20个文档的候选文档集，主要是从这个候选文档集里去做检索的。当然也可以作为reranker配合MDR之类的方法应用到开放域环境。

**Comment by fmm170** [comment]
所以您是从supporting_facts提供的文档中去检索，是我理解这样吗？谢谢～

**Comment by canghongjian** [comment]
> 所以您是从supporting_facts提供的文档中去检索，是我理解这样吗？谢谢～

具体到hotpotqa数据集的话，supporting_facts是标注的相关文档，只有两篇，候选文档集出现在它给的json的context字段里。

**Comment by fmm170** [comment]
针对hotpotqa，您用的是full_wiki版本还是distractor?还想问一下其他数据集用的也是context字段里的吗？（就没有从wiki中检索是吗？）谢谢啦❤️

**Comment by canghongjian** [comment]
目前是在distractor环境进行的实验。其他数据集也是在类似的环境，没有涉及wiki检索。这两天我会上传在hotpotqa fullwiki上进行的beam retrieval作为reranker的代码。

**Comment by fmm170** [comment]
好的谢谢啦～

**Comment by canghongjian** [comment]
Feel free to reopen if there is any further issues!
