### ISSUE TITLE
Request to move weights on huggingface

### ISSUE THREAD

**Issue by Ghost---Shadow** [canghongjian/beam_retriever#7]
Do you have any plans to upload the weights to huggingface, its convenient to use it from there. 

If you are busy, I would be happy to help you.

**Comment by canghongjian** [comment]
Thanks for your advice! I'd appreciate your help. Is there anything specific I should do?

**Comment by Ghost---Shadow** [comment]
It is quite a bit of work. But it really helps everyone else and gets your paper into the millions.

https://huggingface.co/docs/transformers/custom_models

If you are busy, I can also help out if needed.

**Comment by canghongjian** [comment]
OK, I will check it out. If anyone else also thinks this approach is better, please comment here.

**Comment by xiu-ze** [comment]
A good suggestion! It will be convenience for people to experience your work on huggingface! Thank you!
