### ISSUE TITLE
Question about computation cost

### ISSUE THREAD

**Issue by YueChenkkk** [canghongjian/beam_retriever#8]
How is the computation cost of this retrieval algorithm? It seems the text encoder is going to forward k times for a k-hop question, each time with increased input lengths.

**Comment by canghongjian** [comment]
Yes, for a problem with k hops, it requires k encoder calls and k classification head calls, averaging one encoder and one classification head per hop, which is aligning with the resource consumption of previous methods like FE2H and R
 and maintaining a similar order of magnitude in both training and inference.

**Comment by YueChenkkk** [comment]
Thanks for the reply!
